### ISSUE TITLE
Mulig XSS og SQL injection

### ISSUE THREAD

**Issue by melosh101** [Mech654/GhostChat#1]
Først og fremmest, super godt lavet og det er noget du kan være stolt af.
Din kode er super nem at læse og forstå,
Så fortsæt det gode arbejde

Jeg kommer bare for at give noget konstruktiv feedback i forhold til server og client sikkerhed.

## XSS ( Cross site scripting )
XSS er når en client sender noget kode som vil blive kørt når en anden client ser det
https://github.com/Mech654/GhostChat/blob/3b12279facbfcab27944ac454b974ed8e1337690/client/script.js#L52-L59
her bruger du.
```js
div.innerHTML = ` <div >....</div>`
```
innerHTML indsætter alt text som om det var html og det kan føre til XXS
så undgå at bruge den variable vedmindre du styre hvad der kommer til at blive sat ind.
En måde  at fiske det på er at på serveren bliver clientens input saniteret inden det bliver sendt til andre
eller ved at bygge vær af de under elementer der er, og så bruge `div.textContent` til at indsætte brugerens input

et exempel på XSS
send følgende i chatten og hold så musen over det
```js
<b onmouseover=alert('Wufff!')>click me!</b>
``` 

## SQL injection
SQl injection er når brugeren kan angive et input som kan ende med at blive kørt i en sql query

Lige nu ser det ikke ud til at du ikke gemmer beskderne i din SQLITE database men det tænker jeg er din plan
https://github.com/Mech654/GhostChat/blob/3b12279facbfcab27944ac454b974ed8e1337690/server/server.js#L34
dette kan NÆSTEN kun løses ved at sanitere brugerens input før man inputter det i ens query.
Hvis du ikke selv vil sørge for at input dataen er sikker, kan du evt bruge en ORM så som sequelize
Man kan også bruge prepared statements

MVH
a friendly ghost pointed this way by @smallbenji

**Comment by Mech654** [comment]
Mange tak for at have fikset injection-sårbarhederne for mig. Jeg er virkelig glad for den nye databasestruktur, du har lavet (og mange tak for grafen). Mit næste projekt bliver at bygge videre på chat-webappen, implementere din struktur og lave private kanaler mellem brugerne. Jeg har ikke kigget 100% igennem endnu, men ser frem til det.

Beklager forsinkelsen på to uger. Sig hej til @smallbenji, hvis du kan! 😁

**Comment by melosh101** [comment]
Det var så lidt, og er super spændt på hvordan du vil komme frem til de forskellige løsninger, hvis du vil have noget hjælp med Database eller andet kan du bare lave et nyt issue med forklaring og tag mig i det, så vil jeg prøve mit bedste på at komme med en løsning enten via kode eller med råd.
